### ISSUE TITLE
RedisGraph 2.0

### ISSUE THREAD

**Issue by DvirDukhan** [crflynn/redisgraph-ex#10]
Hi @crflynn 
Thanks for the work on this project!
Just a heads up: We released RedisGraph 2.0. As part of this release, we changed the returned resultset format, with the latest modification happened at 1.99.7. 
I case you have any questions, you can reach me at our repo issues page or directly by mail.  
Cheers
Dvir

**Comment by crflynn** [comment]
Thanks for the heads up. I'm watching the releases on https://github.com/RedisGraph/RedisGraph so I should see when newer versions are published. I just updated the elixir version here and should be using the `latest` image when testing locally. The CI workflow now uses redisgraph's `edge` images thanks to @gkorland.
