### ISSUE TITLE
No match on right side error

### ISSUE THREAD

**Issue by AppyCat** [crflynn/redisgraph-ex#6]
Hi Flynn, thank you for your work on this driver. Wanted to give you some feedback, am getting the following error thrown by:

{:ok, commit_result} = RedisGraph.commit(conn, graph)

no match of right hand side value: {:error, %Redix.Error{message: "ERR unknown command `GRAPH.QUERY`, with args beginning with: `social`, `CREATE (mnzrgwxsgl:country{name:'Japan'}),(yzqpcpzdid:person{age:33,gender:'male',name:'John Doe',status:'single'}),(y`, "}}

If I work around it, the result doesn't recognize:

commit_result.statistics

or

QueryResult.pretty_print(query_result)

as valid function properties.

It looks quite good syntax wise, very clean and elegant.

**Comment by crflynn** [comment]
Assuming you are using docker locally, I think you might be running a `redis` image instead of a `redisgraph` image. You can run

`docker run -p 6379:6379 -it --rm redislabs/redisgraph`

to get `redisgraph` running locally. If you choose to run vanilla `redis` I believe there are extra steps for adding the `redisgraph` module.

When I run the example from the readme with `redisgraph` it works fine.

When I run the example from the readme with `redis` I get the same error that you've shared:

```
iex> {:ok, commit_result} = RedisGraph.commit(conn, graph)

08:24:27.138 [debug] GRAPH.QUERY social CREATE (smnmlsvuyi:person{age:33,gender:'male',name:'John Doe',status:'single'}),(syyildpbtm:country{name:'Japan'}),(smnmlsvuyi)-[:visited]->(syyildpbtm) --compact
** (MatchError) no match of right hand side value: {:error, %Redix.Error{message: "ERR unknown command `GRAPH.QUERY`, with args beginning with: `social`, `CREATE (smnmlsvuyi:person{age:33,gender:'male',name:'John Doe',status:'single'}),(syyildpbtm:country{name:'Japan'}),(s`, "}}
    (stdlib) erl_eval.erl:453: :erl_eval.expr/5
    (iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
```

**Comment by AppyCat** [comment]
I was using the redisgraph docker image which I found through the Redisgraph website, the same command you have shared below.

For some reason it won’t work. I even deleted all containers and images related to Redisgraph and Redis and ran the command again as:

docker run -p 6379:6379 -it --rm redislabs/redisgraph

But I still get the same error using the readme code example:

no match of right hand side value: {:error, %Redix.Error{message: "ERR unknown command `GRAPH.QUERY`, with args beginning with: `social`, `CREATE (rfzioqujok:person{age:33,gender:'male',name:'John Doe',status:'single'}),(rlltvfkvzz:country{name:'Japan'}),(r`, "}}

**Comment by AppyCat** [comment]
Btw, I am trying it in Phoenix latest version controller function, not as a stand alone file.

**Comment by crflynn** [comment]
Redix just passes the error response back from interacting with redis. Hence the message 
```
ERR unknown command `GRAPH.QUERY`, with args beginning with: `social`, `CREATE (rfzioqujok:person{age:33,gender:'male',name:'John Doe',status:'single'}),(rlltvfkvzz:country{name:'Japan'}),(r`, "}}
```
indicates that you are communicating with a redis instance which is not setup with the redisgraph module.

You can test this easily with the redis cli:

Using a redis image:
```
% redis-cli
127.0.0.1:6379> graph.query
(error) ERR unknown command `graph.query`, with args beginning with:
```
which indicates that redisgraph is not installed/enabled on redis.

Using a redisgraph image:
```
% redis-cli
127.0.0.1:6379> graph.query
(error) ERR wrong number of arguments for 'graph.query' command
```
which indicates that redisgraph _is_ installed and is expecting additional arguments.

**Comment by AppyCat** [comment]
I don’t believe that’s possible because as I mentioned before, I'm using the Redis graph docker image which has the module included by default, it confirms that in the terminal window.

**Comment by crflynn** [comment]
I'm not sure if there is another way to interpret the error response here. This library doesn't modify the message at all and I doubt that Redix does either.
